version: '3.7'

services:
        web:
                build: 
                        context: .
                        dockerfile: Dockerfile
                command: gunicorn -c gunicorn.config.py --env DJANGO_SETTINGS_MODULE=chp_api.settings chp_api.wsgi:application --bind 0.0.0.0:8000
                volumes:
                        - static_volume:/home/chp_api/web/staticfiles
                expose:
                        - 8000
        db:
                image: postgres:12.0-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                environment:
                        - POSTGRES_USER=chp_api_user
                        - POSTGRES_PASSWORD=chp_api_user
                        - POSTGRES_DB=chp_api_prod
volumes:
        postgres_data:
        static_volume: