version: '3.7'

services:
        db:
                image: postgres:12.0-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
volumes:
        postgres_data:
        static_volume: