version: '3.7'

services:
        web:
                build: 
                        context: .
                        dockerfile: Dockerfile
                command: gunicorn -c gunicorn.config.py --env DJANGO_SETTINGS_MODULE=chp_api.settings chp_api.wsgi:application --bind 0.0.0.0:8000
                volumes:
                        - static_volume:/home/chp_api/web/staticfiles
                expose:
                        - 8000
volumes:
        postgres_data:
        static_volume: